apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-node-sample-multi-component-example-main-h0wo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-node-sample-multi-component-example-main-h0wo
    app.kubernetes.io/part-of: multi-component-application
  name: devfile-node-sample-multi-component-example-main-h0wo
  namespace: e2e-demo-xvyc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-node-sample-multi-component-example-main-h0wo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-node-sample-multi-component-example-main-h0wo
    spec:
      containers:
      - image: quay.io/mkovarik/test-images@sha256:2fba4bbd494e9633771335346f43f30280a0ce0f7189a5db5f3d832a46449a47
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
